import React from 'react'
import Head from 'next/head'

import Toast from '../Toast'

interface LayoutProps {
  children: React.ReactNode
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Boshamlan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="fonts/DroidKufi-Regular.woff2"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="fonts/DroidKufi-Bold.woff2"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Toast />
      <header>Admin Dashboard</header>
      <main>{children}</main>
    </>
  )
}

export default Layout
