import React from 'react'
import Head from 'next/head'

interface LayoutProps {
  children: React.ReactNode
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Boshamlan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="fonts/DroidKufi.woff"
          as="font"
          crossOrigin=""
        />
      </Head>
      <main>{children}</main>
      <footer>footer</footer>
    </>
  )
}

export default Layout
